#!/bin/bash

set -e

echo "Building for Uberspace..."
npm run production

echo "Uploading to Uberspace..."
rsync -ravzulO --chmod=u=rwX,g=rX --exclude-from=.rsync-exclude dist/ uberdennis:html

echo "Building for CDN..."
npm run production -- --assetHost=//dennisreimann-2428.kxcdn.com

echo "Uploading to CDN..."
rsync -ravzulO --chmod=u=rwX,g=rX --exclude-from=.rsync-exclude dist/ dennisreimann@rsync.keycdn.com:zones/dennisreimann/
