#!/bin/bash

set -e

echo "Building..."
npm run production

echo "Uploading to CDN..."
rsync -ravzulO --chmod=u=rwX,g=rX --exclude-from=.rsync-exclude dist/ dennisreimann@rsync.keycdn.com:zones/dennisreimann/

echo "Uploading to Uberspace..."
rsync -ravzulO --chmod=u=rwX,g=rX --exclude-from=.rsync-exclude dist/ uberdennis:html
